### ISSUE TITLE
监控查询报错信息不明确

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-prometheus#101]
**描述您遇到的bug**  
监控对象未安装监控agent，监控查询时报错，提示信息不明确。
![image](https://user-images.githubusercontent.com/17095701/66909782-f07f6f00-f03f-11e9-8e52-cbb58ad24b2e.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by pobu168** [comment]
fixed
