### ISSUE TITLE
监控指标保存修改的建议

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-prometheus#112]
**描述您遇到的bug**  
编辑监控指标保存修改的提示为“新增成功”，建议改提示为“保存成功”。保存成功后建议页面保留原来的监控指标配置信息以便用户二次确认。
![image](https://user-images.githubusercontent.com/17095701/67060974-621b0280-f191-11e9-93bd-7c1323b27b97.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by pobu168** [comment]
提示信息已经修改，保存后保留信息功能尚未支持(用户在保存后可能继续进行设置操作，保留信息可能会增加用户清理动作)
