### ISSUE TITLE
页面切换到对象视图页面有console error

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-prometheus#123]
**描述您遇到的bug**  
页面切换到对象视图页面有console error。
![image](https://user-images.githubusercontent.com/17095701/67172837-75c3a480-f3ef-11e9-9238-25a3c8e8ff7d.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by pobu168** [comment]
fixed
