### ISSUE TITLE
对象视图页面输入非列表里的数据搜索报错

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-prometheus#124]
**描述您遇到的bug**  
对象视图页面输入非列表里的数据搜索报错。
![image](https://user-images.githubusercontent.com/17095701/67172931-d18e2d80-f3ef-11e9-9390-dca473f16a13.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by pobu168** [comment]
fixed
