### ISSUE TITLE
对象视图页面清空日期时报错

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-prometheus#125]
**描述您遇到的bug**  
对象视图页面根据日期搜索后再清空日期时报错。
![image](https://user-images.githubusercontent.com/17095701/67173631-e8ce1a80-f3f1-11e9-9d87-76a3cb8a935f.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by pobu168** [comment]
fixed
