### ISSUE TITLE
在对象视图页面的磁盘或网络视图更改搜索条件页面会跳转到CPU视图

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-prometheus#126]
**描述您遇到的bug**  
在对象视图页面的磁盘或网络视图更改搜索条件页面会跳转到CPU视图。
![image](https://user-images.githubusercontent.com/17095701/67174169-aefe1380-f3f3-11e9-89e2-fab07f6435f1.png)
![image](https://user-images.githubusercontent.com/17095701/67174177-b9b8a880-f3f3-11e9-81fc-50baf81a657c.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by pobu168** [comment]
fixed
