### ISSUE TITLE
监控前端双语校验

### ISSUE THREAD

**Issue by pobu168** [WeBankPartners/wecube-plugins-prometheus#171]
**描述您的需求**  
监控前端双语支持已完成，现邀请大佬对翻译进行校验

**预期行为**  
解决双语翻译中出现的问题

**描述您考虑过的替代方案**  

**附加**

**Comment by yolanda0209** [comment]
[#171中英翻译建议.txt](https://github.com/WeBankPartners/wecube-plugins-prometheus/files/3791781/171.txt)
