### ISSUE TITLE
编辑自定义视图无参数时点击返回报错

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-prometheus#178]
**描述您遇到的bug**  
编辑自定义视图无参数时点击返回报错。
![image](https://user-images.githubusercontent.com/17095701/67744222-e6a43580-fa5b-11e9-938c-afee87db2c40.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by pobu168** [comment]
done
