### ISSUE TITLE
自定义视图的保存按钮无效，对象指标的保存图标不明显

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-prometheus#179]
**描述您遇到的bug**  
自定义视图新增对象指标点击保存按钮无效，点击对象指标的保存图标才保存成功，但是对象指标的保存图标不明显。这两个保存按钮和图标的功能有什么区别？
![image](https://user-images.githubusercontent.com/17095701/67744737-46e7a700-fa5d-11e9-981f-fc762f1bf6c1.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by pobu168** [comment]
此处的页面设计逻辑为：
1、视图已有条件渲染为标签
2、新增条件在选择后确认才生成为可用条件
3、保存按钮对生成标签的条件生效，已选择未确认条件无效

对页面进行了微调，以便更符合操作预期

**Comment by pobu168** [comment]
在视图展示页面增加标题编辑功能，图标编辑页面标题仍使用已有方式编辑
