### ISSUE TITLE
暂时不能监控进程

### ISSUE THREAD

**Issue by DeliaDing123** [WeBankPartners/wecube-plugins-prometheus#215]
**描述您的需求**  
希望能监控进程，并提供选择如果进程挂了可以重新拉起来。

**Comment by nertonsong** [comment]
需要支持进程监控， 可以按用户， 进程名，正则表达式配置监控。
不支持进程拉起， 进程拉起属于变更， 不属于监控系统的功能范围。

**Comment by zgyzgyhero** [comment]
关闭需求，转到 #247
