### ISSUE TITLE
支持指标数据上报

### ISSUE THREAD

**Issue by nertonsong** [WeBankPartners/wecube-plugins-prometheus#226]
**描述您的需求**  
提供HTTP接口，支持外部系统通过HTTP接口上报指标数据，支持单条或者批量上报。
指标上报之后能够在监控系统中查看图形， 配置告警阈值等

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by zgyzgyhero** [comment]
先研究prometheus自带的pushgateway，它支持提供一个类似于缓存的组件供agent主动上报，然后prometheus服务再去它那里拉数据

**Comment by zgyzgyhero** [comment]
关闭需求，转到 #250
