### ISSUE TITLE
阀值管理页面的对象信息列表和实际对象展示不一致

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-prometheus#92]
**描述您遇到的bug**  
监控管理-- 从对象管理页面点击阀值配置按钮跳转到阀值管理页面时，对象信息列表和实际对象展示不一致.
![image](https://user-images.githubusercontent.com/17095701/66908061-0ccddc80-f03d-11e9-8b70-4418726ff82d.png)

![image](https://user-images.githubusercontent.com/17095701/66908121-1fe0ac80-f03d-11e9-9d0a-0ebd10db12fb.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by pobu168** [comment]
fixed
