### ISSUE TITLE
监控管理页面编辑阀值管理时名称不回显

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-prometheus#96]
**描述您遇到的bug**  
监控管理页面编辑阀值管理时名称不回显。
![image](https://user-images.githubusercontent.com/17095701/66909041-af3a8f80-f03e-11e9-8cd5-b6f7c8af937c.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by pobu168** [comment]
fixed
