### ISSUE TITLE
阀值管理和日志管理根据组搜索报错

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-prometheus#98]
**描述您遇到的bug**  
阀值管理和日志管理根据组搜索报错。
![image](https://user-images.githubusercontent.com/17095701/66909605-a0a0a800-f03f-11e9-8bb6-af6657dca7ab.png)
![image](https://user-images.githubusercontent.com/17095701/66909612-a5655c00-f03f-11e9-82fc-afd0473e0aa8.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by pobu168** [comment]
done
