### ISSUE TITLE
搜索内容缓存导致切换页面时查询报错

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-prometheus#99]
**描述您遇到的bug**  
搜索内容缓存导致切换页面时查询报错。
![image](https://user-images.githubusercontent.com/17095701/66909677-bada8600-f03f-11e9-8004-bf8b4cf1a310.png)
![image](https://user-images.githubusercontent.com/17095701/66909692-c332c100-f03f-11e9-8902-cdfe855ce51b.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by pobu168** [comment]
done
